/*
 *   This file will be regenerated by `mulle-sourcetree-to-c --project-dialect objc` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove MulleObjCTimeFoundation`
// (Use EC1666C7-1CB1-4471-A1C6-E5A151FE4B89 instead of MulleObjCTimeFoundation, if there are duplicate entries)
//
// You can tweak the following #import with these commands:
//    remove #import      : `mulle-sde dependency mark MulleObjCTimeFoundation no-header`
//    rename              : `mulle-sde dependency|library set MulleObjCTimeFoundation include whatever.h`
//    reorder             : `mulle-sde dependency move MulleObjCTimeFoundation <up|down>`
//    toggle #import      : `mulle-sde dependency mark MulleObjCTimeFoundation [no-]import`
//    toggle public       : `mulle-sde dependency mark MulleObjCTimeFoundation [no-]public`
//    toggle optional     : `mulle-sde dependency mark MulleObjCTimeFoundation [no-]require`
//    remove for platform : `mulle-sde dependency mark MulleObjCTimeFoundation no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#import <MulleObjCTimeFoundation/MulleObjCTimeFoundation.h>   // MulleObjCTimeFoundation

#ifdef __has_include
# if __has_include( "_MulleObjCLockFoundation-include.h")
#  include "_MulleObjCLockFoundation-include.h"
# endif
#endif

