      { @selector( MulleObjCLoader), @selector( MulleObjCTimeFoundation) },      // 47a9beb6;MulleObjCLoader;cc20d48b;MulleObjCTimeFoundation
      { @selector( NSCondition), @selector( NSDate) },      // 0397143e;NSCondition;cfcedd21;NSDate
      { @selector( NSCondition), MULLE_OBJC_NO_CATEGORYID },      // 0397143e;NSCondition;;
      { @selector( NSConditionLock), @selector( NSDate) },      // 5e0deecf;NSConditionLock;cfcedd21;NSDate
      { @selector( NSConditionLock), MULLE_OBJC_NO_CATEGORYID },      // 5e0deecf;NSConditionLock;;
      { @selector( NSLock), @selector( NSDate) },      // cd92d31f;NSLock;cfcedd21;NSDate
      { @selector( NSLock), MULLE_OBJC_NO_CATEGORYID },      // cd92d31f;NSLock;;
      { @selector( NSRecursiveLock), MULLE_OBJC_NO_CATEGORYID },      // 8ffcedd9;NSRecursiveLock;;
